[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
fs_permissions = [{ access = "read-write", path = "./script/config" }, { access = "read-write", path = "./script/log" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
